import NavBar from "../../components/NavBar";
import PageHead from "../../components/PageHead";
import LpListSection from "../../components/LpListSection";
import SubjectListSection from "../../components/SubjectListSection";

export default function Explore() {
    // Page layout
    // Search (eventually)
    // Filters (by length, difficulty, modality)

    // Sections (Dynamically generated by popularity)
    // Popular (Overall)
    // Section 1
    // Section 2
    // Section 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    // More sections (SubjectList)

    // Within each section: 5 learning paths with summaries, and a link to more learning paths (SubjectLearningPaths)

    return (
        <div>
            <PageHead title="BrainDeck Explore" />
            <NavBar />
            <LpListSection
                title="Most Popular"
                lps={[]}
            />
            <LpListSection
                title="Subject 1"
                lps={[]}
            />
            <LpListSection
                title="Subject 2"
                lps={[]}
            />
            <SubjectListSection
                lpSubjects={[]}
            />
        </div>
    )
}