export default function Home() {
    // Page layout
    // Search (eventually)
    // Filters (by length, difficulty, modality)

    // Sections (Dynamically generated by popularity)
    // Popular (Overall)
    // Section 1
    // Section 2
    // Section 3
    // More sections (SubjectList)

    // Within each section: 5 learning paths with summaries, and a link to more learning paths (SubjectLearningPaths)
    
    return (
        <div>Home</div>
    )
}